# Generated by Django 5.2.6 on 2025-09-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('departure', models.CharField(max_length=36)),
                ('destination', models.CharField(max_length=36)),
                ('departure_at', models.DateTimeField()),
                ('min_price_usd', models.FloatField()),
            ],
        ),
    ]
