# Generated by Django 5.2.6 on 2025-10-06 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='transfers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
