# Generated by Django 5.2.6 on 2025-10-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_text',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_text',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='flights.city'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='flights.city'),
        ),
    ]
