# Generated by Django 5.2.6 on 2025-10-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_departure_text_flight_destination_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='departure_text',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination_text',
        ),
    ]
